// <auto-generated />
using System;
using FinanceTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.DataAccess.Migrations
{
    [DbContext(typeof(FinanceTrackerContext))]
    [Migration("20250324193309_UpdateFinancialOperationCascadeDelete")]
    partial class UpdateFinancialOperationCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Core.Models.BalanceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BalanceChanges");
                });

            modelBuilder.Entity("FinanceTracker.Core.Models.FinancialOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("BalanceChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BalanceChangeId")
                        .IsUnique();

                    b.ToTable("FinancialOperations");
                });

            modelBuilder.Entity("FinanceTracker.Core.Models.FinancialOperation", b =>
                {
                    b.HasOne("FinanceTracker.Core.Models.BalanceChange", "BalanceChange")
                        .WithOne()
                        .HasForeignKey("FinanceTracker.Core.Models.FinancialOperation", "BalanceChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceChange");
                });
#pragma warning restore 612, 618
        }
    }
}
